# Generated by Django 3.2.18 on 2023-06-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckout',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
