# Generated by Django 3.2.18 on 2023-06-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordercheckout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='unique_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
