# Generated by Django 3.2.18 on 2023-06-13 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercheckout_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckout',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
