name: Django Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to remote server
      run: |
        sshpass -p 'password' ssh -o StrictHostKeyChecking=no  user@ip  'cd dexhub/assignment && git pull main'
        sshpass -p 'password' ssh -o StrictHostKeyChecking=no  user@ip  'cd dexhub/assignment &&  docker exec dexhub_app_1 python manage.py migrate'



